version: "3"

services:

    db:
        build: 
            context: ./mysql
        container_name: db
        restart: always
        tty: true
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network

    app:
        build: 
            context: ./node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh
        command: npm start
        tty: true
        networks:
            - node-network
        depends_on: 
            - db

    nginx:
        build: 
            context: ./nginx
        container_name: nginx
        entrypoint: dockerize -wait http://app:3000 -timeout 45s nginx -g "daemon off;"
        networks:
            - node-network
        ports:
            - "8080:80"
        depends_on:
            - app

networks:
    node-network:
        driver: bridge